repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: flake8
      additional_dependencies: ["flake8-string-format"]
      args: [--config, tox.ini]
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, master]

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
